steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/candela/candela-server:latest'
      - '-f'
      - 'deploy/Dockerfile.server'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/candela/candela-server:latest'
