// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: candela/types/chat.proto

use serde::{Deserialize, Serialize};
use serde_json;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "value")]
pub enum ChatEventEvent {
    #[serde(rename = "chunk")]
    Chunk(Box<ChunkEvent>),
    #[serde(rename = "tool_call")]
    ToolCall(Box<ToolCallEvent>),
    #[serde(rename = "status")]
    Status(Box<StatusEvent>),
    #[serde(rename = "done")]
    Done(Box<DoneEvent>),
    #[serde(rename = "error")]
    Error(Box<ErrorEvent>),
}

/// Domain representation of candela.types.ChatEvent.
///
/// ChatEvent is a streaming event emitted during a chat completion.
/// The harness sends these as JSON-RPC notifications to the IDE client.
///
/// Each event carries a stream_id that correlates it to the originating
/// chat.send request.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct ChatEvent {
    pub stream_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event: Option<ChatEventEvent>,
}

/// Domain representation of candela.types.ChunkEvent.
///
/// ChunkEvent is a text delta from the model's streaming response.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct ChunkEvent {
    pub delta: String,
}

/// Domain representation of candela.types.ToolCallEvent.
///
/// ToolCallEvent is emitted when the model requests a tool invocation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct ToolCallEvent {
    pub call_id: String,
    pub tool: String,
    pub args: serde_json::Map<String, serde_json::Value>,
    pub requires_approval: bool,
}

/// Domain representation of candela.types.StatusEvent.
///
/// StatusEvent provides a progress update during generation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct StatusEvent {
    pub text: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
}

/// Domain representation of candela.types.DoneEvent.
///
/// DoneEvent signals successful completion of the stream.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct DoneEvent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<UsageSummary>>,
}

/// Domain representation of candela.types.ErrorEvent.
///
/// ErrorEvent signals that the stream terminated with an error.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct ErrorEvent {
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// Domain representation of candela.types.UsageSummary.
///
/// UsageSummary reports token consumption and cost for a single completion.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]

pub struct UsageSummary {
    pub prompt_tokens: i64,
    pub completion_tokens: i64,
    pub total_tokens: i64,
    pub total_cost_usd: f64,
    pub model: String,
}
