// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: chat.proto
// backend: jsonrpc
//
// NOTE: The From<&ChatEvent> impl below is hand-written (not generated)
// to bridge the domain struct+oneof representation to this flat enum.

use serde::{Deserialize, Serialize};

// Domain types from the sibling `chat` module.
use super::chat::{ChatEvent, ChatEventEvent, UsageSummary};

/// Flat JSON-RPC representation of ChatEvent.
/// Generated from proto message with oneof 'event'.
///
/// Serializes directly to: `{"type":"chunk","stream_id":"...","delta":"..."}`
/// via `#[serde(tag = "type", rename_all = "snake_case")]`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum ChatEventRpc {
    Chunk {
        stream_id: String,
        delta: String,
    },
    ToolCall {
        stream_id: String,
        call_id: String,
        tool: String,
        #[serde(default)]
        args: serde_json::Value,
        requires_approval: bool,
    },
    Status {
        stream_id: String,
        text: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent: Option<String>,
    },
    Done {
        stream_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<UsageSummary>,
    },
    Error {
        stream_id: String,
        message: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        code: Option<String>,
    },
}

// ── Conversion from domain ChatEvent ──
//
// This impl bridges the proto2type domain backend (struct + oneof) to the
// jsonrpc backend (flat tagged enum). It lives here because both ChatEvent
// and ChatEventRpc are defined in candela-types (Rust orphan rule).

impl From<&ChatEvent> for ChatEventRpc {
    fn from(event: &ChatEvent) -> Self {
        let sid = event.stream_id.clone();
        match &event.event {
            Some(ChatEventEvent::Chunk(e)) => ChatEventRpc::Chunk {
                stream_id: sid,
                delta: e.delta.clone(),
            },
            Some(ChatEventEvent::ToolCall(e)) => ChatEventRpc::ToolCall {
                stream_id: sid,
                call_id: e.call_id.clone(),
                tool: e.tool.clone(),
                // Map is already serde_json::Map — wrap directly, no serialize round-trip.
                args: serde_json::Value::Object(e.args.clone()),
                requires_approval: e.requires_approval,
            },
            Some(ChatEventEvent::Status(e)) => ChatEventRpc::Status {
                stream_id: sid,
                text: e.text.clone(),
                agent: e.agent.clone(),
            },
            Some(ChatEventEvent::Done(e)) => ChatEventRpc::Done {
                stream_id: sid,
                usage: e.usage.clone(),
            },
            Some(ChatEventEvent::Error(e)) => ChatEventRpc::Error {
                stream_id: sid,
                message: e.message.clone(),
                code: e.code.clone(),
            },
            // Missing variant → surface as error with UNKNOWN code.
            None => ChatEventRpc::Error {
                stream_id: sid,
                message: "unknown event".into(),
                code: Some("UNKNOWN".into()),
            },
        }
    }
}
