// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: candela/types/chat.proto
// backend: sqlite

use crate::chat::*;
use serde::{Deserialize, Serialize};

#[derive(Debug)]
pub enum ConversionError {
    Json(serde_json::Error),
    Overflow,
}

impl std::fmt::Display for ConversionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Json(e) => write!(f, "json: {e}"),
            Self::Overflow => write!(f, "integer overflow during conversion"),
        }
    }
}

impl std::error::Error for ConversionError {}

impl From<serde_json::Error> for ConversionError {
    fn from(e: serde_json::Error) -> Self {
        Self::Json(e)
    }
}

/// SQLite storage representation of candela.types.ChatEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatEventRow {
    pub stream_id: String,
    pub event: Option<String>,
}

impl ChatEventRow {
    /// Constructs a ChatEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            stream_id: row.get("stream_id")?,
            event: row.get("event")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<ChatEvent, ConversionError> {
        Ok(ChatEvent {
            stream_id: self.stream_id.clone(),
            event: match &self.event {
                Some(s) => Some(serde_json::from_str(s)?),
                None => None,
            },
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<ChatEvent, ConversionError> {
        Ok(ChatEvent {
            stream_id: self.stream_id,
            event: match self.event {
                Some(s) => Some(serde_json::from_str(&s)?),
                None => None,
            },
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &ChatEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            stream_id: d.stream_id.clone(),
            event: match &d.event {
                Some(v) => Some(serde_json::to_string(v)?),
                None => None,
            },
        })
    }
}

impl TryFrom<&ChatEvent> for ChatEventRow {
    type Error = ConversionError;
    fn try_from(d: &ChatEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<ChatEventRow> for ChatEvent {
    type Error = ConversionError;
    fn try_from(row: ChatEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.ChunkEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChunkEventRow {
    pub delta: String,
}

impl ChunkEventRow {
    /// Constructs a ChunkEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            delta: row.get("delta")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<ChunkEvent, ConversionError> {
        Ok(ChunkEvent {
            delta: self.delta.clone(),
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<ChunkEvent, ConversionError> {
        Ok(ChunkEvent { delta: self.delta })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &ChunkEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            delta: d.delta.clone(),
        })
    }
}

impl TryFrom<&ChunkEvent> for ChunkEventRow {
    type Error = ConversionError;
    fn try_from(d: &ChunkEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<ChunkEventRow> for ChunkEvent {
    type Error = ConversionError;
    fn try_from(row: ChunkEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.ToolCallEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCallEventRow {
    pub call_id: String,
    pub tool: String,
    pub args: String,
    pub requires_approval: bool,
}

impl ToolCallEventRow {
    /// Constructs a ToolCallEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            call_id: row.get("call_id")?,
            tool: row.get("tool")?,
            args: row.get("args")?,
            requires_approval: row.get("requires_approval")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<ToolCallEvent, ConversionError> {
        Ok(ToolCallEvent {
            call_id: self.call_id.clone(),
            tool: self.tool.clone(),
            args: serde_json::from_str(&self.args)?,
            requires_approval: self.requires_approval,
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<ToolCallEvent, ConversionError> {
        Ok(ToolCallEvent {
            call_id: self.call_id,
            tool: self.tool,
            args: serde_json::from_str(&self.args)?,
            requires_approval: self.requires_approval,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &ToolCallEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            call_id: d.call_id.clone(),
            tool: d.tool.clone(),
            args: serde_json::to_string(&d.args)?,
            requires_approval: d.requires_approval,
        })
    }
}

impl TryFrom<&ToolCallEvent> for ToolCallEventRow {
    type Error = ConversionError;
    fn try_from(d: &ToolCallEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<ToolCallEventRow> for ToolCallEvent {
    type Error = ConversionError;
    fn try_from(row: ToolCallEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.StatusEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StatusEventRow {
    pub text: String,
    pub agent: Option<String>,
}

impl StatusEventRow {
    /// Constructs a StatusEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            text: row.get("text")?,
            agent: row.get("agent")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<StatusEvent, ConversionError> {
        Ok(StatusEvent {
            text: self.text.clone(),
            agent: self.agent.clone(),
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<StatusEvent, ConversionError> {
        Ok(StatusEvent {
            text: self.text,
            agent: self.agent,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &StatusEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            text: d.text.clone(),
            agent: d.agent.clone(),
        })
    }
}

impl TryFrom<&StatusEvent> for StatusEventRow {
    type Error = ConversionError;
    fn try_from(d: &StatusEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<StatusEventRow> for StatusEvent {
    type Error = ConversionError;
    fn try_from(row: StatusEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.DoneEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DoneEventRow {
    pub usage: Option<String>,
}

impl DoneEventRow {
    /// Constructs a DoneEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            usage: row.get("usage")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<DoneEvent, ConversionError> {
        Ok(DoneEvent {
            usage: match &self.usage {
                Some(s) => Some(serde_json::from_str(s)?),
                None => None,
            },
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<DoneEvent, ConversionError> {
        Ok(DoneEvent {
            usage: match self.usage {
                Some(s) => Some(serde_json::from_str(&s)?),
                None => None,
            },
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &DoneEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            usage: match &d.usage {
                Some(v) => Some(serde_json::to_string(v)?),
                None => None,
            },
        })
    }
}

impl TryFrom<&DoneEvent> for DoneEventRow {
    type Error = ConversionError;
    fn try_from(d: &DoneEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<DoneEventRow> for DoneEvent {
    type Error = ConversionError;
    fn try_from(row: DoneEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.ErrorEvent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ErrorEventRow {
    pub message: String,
    pub code: Option<String>,
}

impl ErrorEventRow {
    /// Constructs a ErrorEventRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            message: row.get("message")?,
            code: row.get("code")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<ErrorEvent, ConversionError> {
        Ok(ErrorEvent {
            message: self.message.clone(),
            code: self.code.clone(),
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<ErrorEvent, ConversionError> {
        Ok(ErrorEvent {
            message: self.message,
            code: self.code,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &ErrorEvent) -> Result<Self, ConversionError> {
        Ok(Self {
            message: d.message.clone(),
            code: d.code.clone(),
        })
    }
}

impl TryFrom<&ErrorEvent> for ErrorEventRow {
    type Error = ConversionError;
    fn try_from(d: &ErrorEvent) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<ErrorEventRow> for ErrorEvent {
    type Error = ConversionError;
    fn try_from(row: ErrorEventRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}

/// SQLite storage representation of candela.types.UsageSummary.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UsageSummaryRow {
    pub prompt_tokens: i64,
    pub completion_tokens: i64,
    pub total_tokens: i64,
    pub total_cost_usd: f64,
    pub model: String,
}

impl UsageSummaryRow {
    /// Constructs a UsageSummaryRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            prompt_tokens: row.get("prompt_tokens")?,
            completion_tokens: row.get("completion_tokens")?,
            total_tokens: row.get("total_tokens")?,
            total_cost_usd: row.get("total_cost_usd")?,
            model: row.get("model")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<UsageSummary, ConversionError> {
        Ok(UsageSummary {
            prompt_tokens: self.prompt_tokens,
            completion_tokens: self.completion_tokens,
            total_tokens: self.total_tokens,
            total_cost_usd: self.total_cost_usd,
            model: self.model.clone(),
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<UsageSummary, ConversionError> {
        Ok(UsageSummary {
            prompt_tokens: self.prompt_tokens,
            completion_tokens: self.completion_tokens,
            total_tokens: self.total_tokens,
            total_cost_usd: self.total_cost_usd,
            model: self.model,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &UsageSummary) -> Result<Self, ConversionError> {
        Ok(Self {
            prompt_tokens: d.prompt_tokens,
            completion_tokens: d.completion_tokens,
            total_tokens: d.total_tokens,
            total_cost_usd: d.total_cost_usd,
            model: d.model.clone(),
        })
    }
}

impl TryFrom<&UsageSummary> for UsageSummaryRow {
    type Error = ConversionError;
    fn try_from(d: &UsageSummary) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<UsageSummaryRow> for UsageSummary {
    type Error = ConversionError;
    fn try_from(row: UsageSummaryRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}
