//! Vendored proto2type-generated Rust types from candela-protos.
//!
//! These files are generated by proto2type and should not be edited manually.
//! To regenerate, run from the candela-protos repo:
//!
//! ```bash
//! buf generate --template buf.gen.rust.yaml
//! ```
//!
//! Then copy the relevant files from gen/rust/.../ into this crate.

pub mod chat;
pub mod chat_jsonrpc;
pub mod chat_sqlite;
pub mod model_catalog;
pub mod model_catalog_sqlite;
pub mod session;
pub mod session_sqlite;
