// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: candela/types/model_catalog.proto
// backend: sqlite

use crate::model_catalog::*;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug)]
pub enum ConversionError {
    Json(serde_json::Error),
    InvalidTimestamp(i64),
    Overflow,
}

impl std::fmt::Display for ConversionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Json(e) => write!(f, "json: {e}"),
            Self::InvalidTimestamp(ms) => write!(f, "invalid timestamp: {ms}ms"),
            Self::Overflow => write!(f, "integer overflow during conversion"),
        }
    }
}

impl std::error::Error for ConversionError {}

impl From<serde_json::Error> for ConversionError {
    fn from(e: serde_json::Error) -> Self {
        Self::Json(e)
    }
}

/// Converts epoch milliseconds to a chrono DateTime<Utc>.
#[allow(dead_code)]
fn epoch_ms_to_datetime(ms: i64) -> Result<DateTime<Utc>, ConversionError> {
    DateTime::from_timestamp_millis(ms).ok_or(ConversionError::InvalidTimestamp(ms))
}

/// Converts a chrono DateTime<Utc> to epoch milliseconds.
#[allow(dead_code)]
fn datetime_to_epoch_ms(dt: &DateTime<Utc>) -> i64 {
    dt.timestamp_millis()
}

/// SQLite storage representation of candela.types.ModelCatalogEntry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelCatalogEntryRow {
    pub model_id: String,
    pub provider: String,
    pub display_name: String,
    pub input_per_million: f64,
    pub output_per_million: f64,
    pub enabled: bool,
    pub category: String,
    pub context_window: i64,
    pub input_per_million_high: f64,
    pub output_per_million_high: f64,
    pub tier_threshold_tokens: i64,
    pub aliases: String,
    pub allowed_tenants: String,
    pub discount_percent: f64,
    pub updated_at: i64,
    pub provider_model_id: String,
    pub region: String,
}

impl ModelCatalogEntryRow {
    /// Constructs a ModelCatalogEntryRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            model_id: row.get("model_id")?,
            provider: row.get("provider")?,
            display_name: row.get("display_name")?,
            input_per_million: row.get("input_per_million")?,
            output_per_million: row.get("output_per_million")?,
            enabled: row.get("enabled")?,
            category: row.get("category")?,
            context_window: row.get("context_window")?,
            input_per_million_high: row.get("input_per_million_high")?,
            output_per_million_high: row.get("output_per_million_high")?,
            tier_threshold_tokens: row.get("tier_threshold_tokens")?,
            aliases: row.get("aliases")?,
            allowed_tenants: row.get("allowed_tenants")?,
            discount_percent: row.get("discount_percent")?,
            updated_at: row.get("updated_at")?,
            provider_model_id: row.get("provider_model_id")?,
            region: row.get("region")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<ModelCatalogEntry, ConversionError> {
        Ok(ModelCatalogEntry {
            model_id: self.model_id.clone(),
            provider: self.provider.clone(),
            display_name: self.display_name.clone(),
            input_per_million: self.input_per_million,
            output_per_million: self.output_per_million,
            enabled: self.enabled,
            category: self.category.clone(),
            context_window: self.context_window,
            input_per_million_high: self.input_per_million_high,
            output_per_million_high: self.output_per_million_high,
            tier_threshold_tokens: self.tier_threshold_tokens,
            aliases: serde_json::from_str(&self.aliases)?,
            allowed_tenants: serde_json::from_str(&self.allowed_tenants)?,
            discount_percent: self.discount_percent,
            updated_at: epoch_ms_to_datetime(self.updated_at)?,
            provider_model_id: self.provider_model_id.clone(),
            region: self.region.clone(),
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<ModelCatalogEntry, ConversionError> {
        Ok(ModelCatalogEntry {
            model_id: self.model_id,
            provider: self.provider,
            display_name: self.display_name,
            input_per_million: self.input_per_million,
            output_per_million: self.output_per_million,
            enabled: self.enabled,
            category: self.category,
            context_window: self.context_window,
            input_per_million_high: self.input_per_million_high,
            output_per_million_high: self.output_per_million_high,
            tier_threshold_tokens: self.tier_threshold_tokens,
            aliases: serde_json::from_str(&self.aliases)?,
            allowed_tenants: serde_json::from_str(&self.allowed_tenants)?,
            discount_percent: self.discount_percent,
            updated_at: epoch_ms_to_datetime(self.updated_at)?,
            provider_model_id: self.provider_model_id,
            region: self.region,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &ModelCatalogEntry) -> Result<Self, ConversionError> {
        Ok(Self {
            model_id: d.model_id.clone(),
            provider: d.provider.clone(),
            display_name: d.display_name.clone(),
            input_per_million: d.input_per_million,
            output_per_million: d.output_per_million,
            enabled: d.enabled,
            category: d.category.clone(),
            context_window: d.context_window,
            input_per_million_high: d.input_per_million_high,
            output_per_million_high: d.output_per_million_high,
            tier_threshold_tokens: d.tier_threshold_tokens,
            aliases: serde_json::to_string(&d.aliases)?,
            allowed_tenants: serde_json::to_string(&d.allowed_tenants)?,
            discount_percent: d.discount_percent,
            updated_at: datetime_to_epoch_ms(&d.updated_at),
            provider_model_id: d.provider_model_id.clone(),
            region: d.region.clone(),
        })
    }
}

impl TryFrom<&ModelCatalogEntry> for ModelCatalogEntryRow {
    type Error = ConversionError;
    fn try_from(d: &ModelCatalogEntry) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<ModelCatalogEntryRow> for ModelCatalogEntry {
    type Error = ConversionError;
    fn try_from(row: ModelCatalogEntryRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}
