// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.4.2
// source: candela/types/model_catalog.proto

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Domain representation of candela.types.ModelCatalogEntry.
///
/// ModelCatalogEntry represents a single model in the catalog with its
/// pricing, metadata, and visibility state.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ModelCatalogEntry {
    pub model_id: String,
    pub provider: String,
    pub display_name: String,
    pub input_per_million: f64,
    pub output_per_million: f64,
    pub enabled: bool,
    pub category: String,
    pub context_window: i64,
    pub input_per_million_high: f64,
    pub output_per_million_high: f64,
    pub tier_threshold_tokens: i64,
    #[serde(default)]
    pub aliases: Vec<String>,
    #[serde(default)]
    pub allowed_tenants: Vec<String>,
    pub discount_percent: f64,
    pub updated_at: DateTime<Utc>,
    pub provider_model_id: String,
    pub region: String,
    #[serde(default)]
    pub required_access: Vec<String>,
}
