// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: candela/types/session.proto

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// MessageRole identifies who authored a chat message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[repr(i32)]
pub enum MessageRole {
    #[default]
    Unspecified = 0,
    User = 1,
    Assistant = 2,
    System = 3,
    Tool = 4,
}

impl MessageRole {
    pub fn from_i32(value: i32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::User),
            2 => Some(Self::Assistant),
            3 => Some(Self::System),
            4 => Some(Self::Tool),
            _ => None,
        }
    }
}

impl std::fmt::Display for MessageRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unspecified => write!(f, "MESSAGE_ROLE_UNSPECIFIED"),
            Self::User => write!(f, "MESSAGE_ROLE_USER"),
            Self::Assistant => write!(f, "MESSAGE_ROLE_ASSISTANT"),
            Self::System => write!(f, "MESSAGE_ROLE_SYSTEM"),
            Self::Tool => write!(f, "MESSAGE_ROLE_TOOL"),
        }
    }
}

/// Domain representation of candela.types.Session.
///
/// Session represents a single conversation between a user and an AI model.
/// Each session contains an ordered sequence of messages and tracks aggregate
/// usage metrics for cost accounting.
///
/// Storage: SQLite (local harness), Firestore (cloud sync)
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Session {
    pub id: String,
    pub title: String,
    pub model: String,
    pub message_count: i32,
    pub total_tokens: i64,
    pub total_cost_usd: f64,
    pub device_id: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,
}

/// Domain representation of candela.types.Message.
///
/// Message is a single turn in a chat session.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Message {
    pub id: String,
    pub session_id: String,
    pub role: MessageRole,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token_count: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
    pub created_at: DateTime<Utc>,
    pub sequence: i64,
}

/// Domain representation of candela.types.SearchResult.
///
/// SearchResult is a ranked match from full-text search across sessions.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SearchResult {
    pub session_id: String,
    pub message_id: String,
    pub session_title: String,
    pub message_preview: String,
    pub role: MessageRole,
    pub score: f64,
    pub created_at: DateTime<Utc>,
}
