// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.3.0
// source: candela/types/session.proto
// backend: sqlite

use crate::session::*;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug)]
pub enum ConversionError {
    Json(serde_json::Error),
    InvalidTimestamp(i64),
    Overflow,
}

impl std::fmt::Display for ConversionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Json(e) => write!(f, "json: {e}"),
            Self::InvalidTimestamp(ms) => write!(f, "invalid timestamp: {ms}ms"),
            Self::Overflow => write!(f, "integer overflow during conversion"),
        }
    }
}

impl std::error::Error for ConversionError {}

impl From<serde_json::Error> for ConversionError {
    fn from(e: serde_json::Error) -> Self {
        Self::Json(e)
    }
}

/// Converts epoch milliseconds to a chrono DateTime<Utc>.
#[allow(dead_code)]
fn epoch_ms_to_datetime(ms: i64) -> Result<DateTime<Utc>, ConversionError> {
    DateTime::from_timestamp_millis(ms).ok_or(ConversionError::InvalidTimestamp(ms))
}

/// Converts a chrono DateTime<Utc> to epoch milliseconds.
#[allow(dead_code)]
fn datetime_to_epoch_ms(dt: &DateTime<Utc>) -> i64 {
    dt.timestamp_millis()
}

/// SQLite storage representation of candela.types.Session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionRow {
    pub title: String,
    pub model: String,
    pub message_count: i32,
    pub total_tokens: i64,
    pub total_cost_usd: f64,
    pub device_id: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub deleted_at: Option<i64>,
}

impl SessionRow {
    /// Constructs a SessionRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            title: row.get("title")?,
            model: row.get("model")?,
            message_count: row.get("message_count")?,
            total_tokens: row.get("total_tokens")?,
            total_cost_usd: row.get("total_cost_usd")?,
            device_id: row.get("device_id")?,
            created_at: row.get("created_at")?,
            updated_at: row.get("updated_at")?,
            deleted_at: row.get("deleted_at")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self, id: String) -> Result<Session, ConversionError> {
        Ok(Session {
            id,
            title: self.title.clone(),
            model: self.model.clone(),
            message_count: self.message_count,
            total_tokens: self.total_tokens,
            total_cost_usd: self.total_cost_usd,
            device_id: self.device_id.clone(),
            created_at: epoch_ms_to_datetime(self.created_at)?,
            updated_at: epoch_ms_to_datetime(self.updated_at)?,
            deleted_at: match self.deleted_at {
                Some(ms) => Some(epoch_ms_to_datetime(ms)?),
                None => None,
            },
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self, id: String) -> Result<Session, ConversionError> {
        Ok(Session {
            id,
            title: self.title,
            model: self.model,
            message_count: self.message_count,
            total_tokens: self.total_tokens,
            total_cost_usd: self.total_cost_usd,
            device_id: self.device_id,
            created_at: epoch_ms_to_datetime(self.created_at)?,
            updated_at: epoch_ms_to_datetime(self.updated_at)?,
            deleted_at: match self.deleted_at {
                Some(ms) => Some(epoch_ms_to_datetime(ms)?),
                None => None,
            },
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &Session) -> Result<Self, ConversionError> {
        Ok(Self {
            title: d.title.clone(),
            model: d.model.clone(),
            message_count: d.message_count,
            total_tokens: d.total_tokens,
            total_cost_usd: d.total_cost_usd,
            device_id: d.device_id.clone(),
            created_at: datetime_to_epoch_ms(&d.created_at),
            updated_at: datetime_to_epoch_ms(&d.updated_at),
            deleted_at: d.deleted_at.as_ref().map(datetime_to_epoch_ms),
        })
    }
}

impl TryFrom<&Session> for SessionRow {
    type Error = ConversionError;
    fn try_from(d: &Session) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

/// SQLite storage representation of candela.types.Message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MessageRow {
    pub session_id: String,
    pub role: i32,
    pub content: String,
    pub model: Option<String>,
    pub token_count: Option<i32>,
    pub cost_usd: Option<f64>,
    pub created_at: i64,
    pub sequence: i64,
}

impl MessageRow {
    /// Constructs a MessageRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            session_id: row.get("session_id")?,
            role: row.get("role")?,
            content: row.get("content")?,
            model: row.get("model")?,
            token_count: row.get("token_count")?,
            cost_usd: row.get("cost_usd")?,
            created_at: row.get("created_at")?,
            sequence: row.get("sequence")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self, id: String) -> Result<Message, ConversionError> {
        Ok(Message {
            id,
            session_id: self.session_id.clone(),
            role: MessageRole::from_i32(self.role).unwrap_or_default(),
            content: self.content.clone(),
            model: self.model.clone(),
            token_count: self.token_count,
            cost_usd: self.cost_usd,
            created_at: epoch_ms_to_datetime(self.created_at)?,
            sequence: self.sequence,
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self, id: String) -> Result<Message, ConversionError> {
        Ok(Message {
            id,
            session_id: self.session_id,
            role: MessageRole::from_i32(self.role).unwrap_or_default(),
            content: self.content,
            model: self.model,
            token_count: self.token_count,
            cost_usd: self.cost_usd,
            created_at: epoch_ms_to_datetime(self.created_at)?,
            sequence: self.sequence,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &Message) -> Result<Self, ConversionError> {
        Ok(Self {
            session_id: d.session_id.clone(),
            role: d.role as i32,
            content: d.content.clone(),
            model: d.model.clone(),
            token_count: d.token_count,
            cost_usd: d.cost_usd,
            created_at: datetime_to_epoch_ms(&d.created_at),
            sequence: d.sequence,
        })
    }
}

impl TryFrom<&Message> for MessageRow {
    type Error = ConversionError;
    fn try_from(d: &Message) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

/// SQLite storage representation of candela.types.SearchResult.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SearchResultRow {
    pub session_id: String,
    pub message_id: String,
    pub session_title: String,
    pub message_preview: String,
    pub role: i32,
    pub score: f64,
    pub created_at: i64,
}

impl SearchResultRow {
    /// Constructs a SearchResultRow from a rusqlite::Row using named column access.
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            session_id: row.get("session_id")?,
            message_id: row.get("message_id")?,
            session_title: row.get("session_title")?,
            message_preview: row.get("message_preview")?,
            role: row.get("role")?,
            score: row.get("score")?,
            created_at: row.get("created_at")?,
        })
    }

    /// Converts this row to the domain type.
    pub fn to_domain(&self) -> Result<SearchResult, ConversionError> {
        Ok(SearchResult {
            session_id: self.session_id.clone(),
            message_id: self.message_id.clone(),
            session_title: self.session_title.clone(),
            message_preview: self.message_preview.clone(),
            role: MessageRole::from_i32(self.role).unwrap_or_default(),
            score: self.score,
            created_at: epoch_ms_to_datetime(self.created_at)?,
        })
    }

    /// Converts this row into the domain type, consuming self.
    pub fn into_domain(self) -> Result<SearchResult, ConversionError> {
        Ok(SearchResult {
            session_id: self.session_id,
            message_id: self.message_id,
            session_title: self.session_title,
            message_preview: self.message_preview,
            role: MessageRole::from_i32(self.role).unwrap_or_default(),
            score: self.score,
            created_at: epoch_ms_to_datetime(self.created_at)?,
        })
    }

    /// Constructs a row from the domain type.
    pub fn from_domain(d: &SearchResult) -> Result<Self, ConversionError> {
        Ok(Self {
            session_id: d.session_id.clone(),
            message_id: d.message_id.clone(),
            session_title: d.session_title.clone(),
            message_preview: d.message_preview.clone(),
            role: d.role as i32,
            score: d.score,
            created_at: datetime_to_epoch_ms(&d.created_at),
        })
    }
}

impl TryFrom<&SearchResult> for SearchResultRow {
    type Error = ConversionError;
    fn try_from(d: &SearchResult) -> Result<Self, Self::Error> {
        Self::from_domain(d)
    }
}

impl TryFrom<SearchResultRow> for SearchResult {
    type Error = ConversionError;
    fn try_from(row: SearchResultRow) -> Result<Self, Self::Error> {
        row.into_domain()
    }
}
