//! Domain types, configuration, and errors for the candela-harness IDE sidecar.
//!
//! Session, Message, MessageRole, SearchResult, UsageSummary, and ChatEvent are
//! re-exported from `candela-types` (generated from candela-protos).
//! HarnessConfig, HarnessError, and TransportMode remain harness-specific
//! and are defined here.

use serde::{Deserialize, Serialize};

// ── Re-exported proto-generated types ──

pub use candela_types::chat::UsageSummary;
pub use candela_types::session::{Message, MessageRole, SearchResult, Session};

// ── Session constructor ──

/// Extension methods for creating new sessions.
pub fn new_session(model: &str, device_id: &str) -> Session {
    let now = chrono::Utc::now();
    let id = uuid::Uuid::new_v4().to_string();
    Session {
        id,
        title: "New Chat".to_string(),
        model: model.to_string(),
        message_count: 0,
        total_tokens: 0,
        total_cost_usd: 0.0,
        device_id: device_id.to_string(),
        created_at: now,
        updated_at: now,
        deleted_at: None,
    }
}

/// Create a new user message for a session.
pub fn new_message(session_id: &str, role: MessageRole, content: &str) -> Message {
    Message {
        id: uuid::Uuid::new_v4().to_string(),
        session_id: session_id.to_string(),
        role,
        content: content.to_string(),
        created_at: chrono::Utc::now(),
        ..Default::default()
    }
}

// ── Configuration ──

/// Top-level harness configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HarnessConfig {
    /// Directory for session storage.
    pub save_dir: std::path::PathBuf,
    /// Candela proxy URL for model routing.
    pub proxy_url: Option<String>,
    /// Default model identifier.
    pub model: String,
    /// Budget limit in USD. 0 = unlimited.
    // TODO: Consider using integer micro-units (i64 microdollars) instead of f64
    // to avoid floating-point rounding in budget calculations.
    pub budget_limit_usd: f64,
    /// Device ID for cross-device sync.
    pub device_id: String,
    /// Enable subagent delegation.
    pub enable_subagents: bool,
    /// Transport mode.
    pub transport: TransportMode,
    /// HTTP port (for daemon mode).
    pub http_port: u16,
    /// Model for auto-generating session titles.
    /// Some("truncate") (default) = first ~80 chars, word-boundary aware.
    /// Some("keywords") = local keyword extraction, no API call.
    /// Some("auto") = resolve cheapest model at runtime via models.list API.
    /// Some("model-name") = use a specific model for LLM summarization.
    /// None = disabled, no auto-titling.
    #[serde(default = "default_auto_title_model")]
    pub auto_title_model: Option<String>,
}

fn default_auto_title_model() -> Option<String> {
    Some("truncate".to_string())
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum TransportMode {
    #[default]
    Stdio,
    Http,
}

impl Default for HarnessConfig {
    fn default() -> Self {
        Self {
            save_dir: std::path::PathBuf::from(".candela/sessions"),
            proxy_url: None,
            model: "gemini-2.0-flash".to_string(),
            budget_limit_usd: 5.0,
            device_id: String::new(),
            enable_subagents: true,
            transport: TransportMode::Stdio,
            http_port: 8200,
            auto_title_model: Some("truncate".to_string()),
        }
    }
}

// ── Errors ──

/// Harness-specific error type.
#[derive(Debug, thiserror::Error)]
pub enum HarnessError {
    #[error("storage error: {0}")]
    Storage(String),

    #[error("serialization error: {0}")]
    Serialization(#[from] serde_json::Error),

    #[error("session not found: {0}")]
    SessionNotFound(String),

    #[error("budget exceeded: used ${used:.4} of ${limit:.4} limit")]
    BudgetExceeded { used: f64, limit: f64 },

    #[error("transport error: {0}")]
    Transport(String),

    #[error("{0}")]
    Other(#[from] anyhow::Error),
}

// ── Streaming Chat Events ──
//
// The canonical ChatEvent is generated by proto2type from candela.types.chat
// and re-exported here. It uses a struct + oneof pattern:
//
//   ChatEvent { stream_id, event: Option<ChatEventEvent> }
//
// For JSON-RPC wire format (flat `{"type":"chunk","stream_id":"...","delta":"..."}`),
// use `chat_event_to_json_value()` below.

pub use candela_types::chat::{
    ChatEvent, ChatEventEvent, ChunkEvent, DoneEvent, ErrorEvent, StatusEvent, ToolCallEvent,
};

/// Convert a ChatEvent to a flat JSON value for JSON-RPC notifications.
///
/// Produces: `{"type": "chunk", "stream_id": "...", "delta": "..."}`
/// This matches the wire format that IDE clients expect over stdio.
pub fn chat_event_to_json_value(event: &ChatEvent) -> serde_json::Value {
    match &event.event {
        Some(ChatEventEvent::Chunk(e)) => serde_json::json!({
            "type": "chunk",
            "stream_id": event.stream_id,
            "delta": e.delta,
        }),
        Some(ChatEventEvent::ToolCall(e)) => serde_json::json!({
            "type": "tool_call",
            "stream_id": event.stream_id,
            "call_id": e.call_id,
            "tool": e.tool,
            "args": e.args,
            "requires_approval": e.requires_approval,
        }),
        Some(ChatEventEvent::Status(e)) => {
            let mut v = serde_json::json!({
                "type": "status",
                "stream_id": event.stream_id,
                "text": e.text,
            });
            if let Some(agent) = &e.agent {
                v["agent"] = serde_json::Value::String(agent.clone());
            }
            v
        }
        Some(ChatEventEvent::Done(e)) => {
            let mut v = serde_json::json!({
                "type": "done",
                "stream_id": event.stream_id,
            });
            if let Some(usage) = &e.usage {
                v["usage"] = serde_json::to_value(usage.as_ref()).unwrap_or_default();
            }
            v
        }
        Some(ChatEventEvent::Error(e)) => {
            let mut v = serde_json::json!({
                "type": "error",
                "stream_id": event.stream_id,
                "message": e.message,
            });
            if let Some(code) = &e.code {
                v["code"] = serde_json::Value::String(code.clone());
            }
            v
        }
        None => serde_json::json!({
            "type": "unknown",
            "stream_id": event.stream_id,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_new_has_valid_defaults() {
        let session = new_session("gemini-2.0-flash", "device-1");
        assert_eq!(session.title, "New Chat");
        assert_eq!(session.model, "gemini-2.0-flash");
        assert_eq!(session.message_count, 0);
        assert!(session.deleted_at.is_none());
        assert!(!session.id.is_empty());
    }

    #[test]
    fn session_json_round_trip() {
        let session = new_session("test-model", "dev-1");
        let json = serde_json::to_string(&session).unwrap();
        let restored: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.id, session.id);
        assert_eq!(restored.model, "test-model");
    }

    #[test]
    fn chat_event_json_rpc_round_trip() {
        let event = ChatEvent {
            stream_id: "s1".into(),
            event: Some(ChatEventEvent::Done(Box::new(DoneEvent {
                usage: Some(Box::new(UsageSummary::default())),
            }))),
        };
        let json = chat_event_to_json_value(&event);
        assert_eq!(json["type"], "done");
        assert_eq!(json["stream_id"], "s1");
    }

    #[test]
    fn message_new_has_uuid() {
        let msg = new_message("sess-1", MessageRole::User, "hello");
        assert!(!msg.id.is_empty());
        assert_eq!(msg.session_id, "sess-1");
        assert_eq!(msg.content, "hello");
    }

    #[test]
    fn harness_config_default() {
        let config = HarnessConfig::default();
        assert_eq!(config.model, "gemini-2.0-flash");
        assert_eq!(config.http_port, 8200);
    }

    #[test]
    fn test_chat_event_all_variants_json_rpc() {
        // Verify chat_event_to_json_value produces the correct flat format
        // for each variant.
        let cases: Vec<(ChatEvent, &str)> = vec![
            (
                ChatEvent {
                    stream_id: "s1".into(),
                    event: Some(ChatEventEvent::Chunk(Box::new(ChunkEvent {
                        delta: "Hello".into(),
                    }))),
                },
                "chunk",
            ),
            (
                ChatEvent {
                    stream_id: "s1".into(),
                    event: Some(ChatEventEvent::ToolCall(Box::new(ToolCallEvent {
                        call_id: "c1".into(),
                        tool: "read_file".into(),
                        args: serde_json::Map::new(),
                        requires_approval: true,
                    }))),
                },
                "tool_call",
            ),
            (
                ChatEvent {
                    stream_id: "s1".into(),
                    event: Some(ChatEventEvent::Status(Box::new(StatusEvent {
                        text: "Analyzing...".into(),
                        agent: Some("sub-1".into()),
                    }))),
                },
                "status",
            ),
            (
                ChatEvent {
                    stream_id: "s1".into(),
                    event: Some(ChatEventEvent::Error(Box::new(ErrorEvent {
                        message: "rate limit".into(),
                        code: None,
                    }))),
                },
                "error",
            ),
            (
                ChatEvent {
                    stream_id: "s1".into(),
                    event: Some(ChatEventEvent::Done(Box::new(DoneEvent {
                        usage: Some(Box::new(UsageSummary::default())),
                    }))),
                },
                "done",
            ),
        ];

        for (event, expected_type) in &cases {
            let json = chat_event_to_json_value(event);
            assert_eq!(
                json["type"].as_str().unwrap(),
                *expected_type,
                "wrong type for {expected_type}"
            );
            assert_eq!(json["stream_id"], "s1");
        }
    }

    #[test]
    fn test_chat_event_json_rpc_chunk_has_delta() {
        let event = ChatEvent {
            stream_id: "s1".into(),
            event: Some(ChatEventEvent::Chunk(Box::new(ChunkEvent {
                delta: "Hello world".into(),
            }))),
        };
        let json = chat_event_to_json_value(&event);
        assert_eq!(json["delta"], "Hello world");
    }

    #[test]
    fn test_chat_event_json_rpc_status_with_agent() {
        let event = ChatEvent {
            stream_id: "s1".into(),
            event: Some(ChatEventEvent::Status(Box::new(StatusEvent {
                text: "Working...".into(),
                agent: Some("sub-agent".into()),
            }))),
        };
        let json = chat_event_to_json_value(&event);
        assert_eq!(json["agent"], "sub-agent");
    }

    #[test]
    fn test_chat_event_json_rpc_status_without_agent() {
        let event = ChatEvent {
            stream_id: "s1".into(),
            event: Some(ChatEventEvent::Status(Box::new(StatusEvent {
                text: "Working...".into(),
                agent: None,
            }))),
        };
        let json = chat_event_to_json_value(&event);
        assert!(json.get("agent").is_none());
    }

    #[test]
    fn test_new_message_sets_defaults() {
        let msg = new_message("sess-1", MessageRole::Assistant, "hi");
        // model should be None (from Default).
        assert_eq!(msg.model, None);
        // token_count should be None.
        assert_eq!(msg.token_count, None);
        // sequence defaults to 0 (DB auto-assigns on insert).
        assert_eq!(msg.sequence, 0);
        // cost_usd should be None.
        assert_eq!(msg.cost_usd, None);
    }

    #[test]
    fn test_serde_missing_auto_title_model_defaults_to_truncate() {
        // Configs from older versions won't have auto_title_model.
        // The serde default should fill in Some("truncate"), not None.
        let json = r#"{
            "save_dir": ".candela/sessions",
            "model": "gemini-2.0-flash",
            "budget_limit_usd": 5.0,
            "device_id": "",
            "enable_subagents": true,
            "transport": "stdio",
            "http_port": 8200
        }"#;
        let config: HarnessConfig = serde_json::from_str(json).unwrap();
        assert_eq!(
            config.auto_title_model,
            Some("truncate".to_string()),
            "missing auto_title_model should default to Some(\"truncate\")"
        );
    }

    #[test]
    fn test_serde_explicit_none_auto_title_model() {
        // Explicitly set to null = disabled.
        let json = r#"{
            "save_dir": ".candela/sessions",
            "model": "gemini-2.0-flash",
            "budget_limit_usd": 5.0,
            "device_id": "",
            "enable_subagents": true,
            "transport": "stdio",
            "http_port": 8200,
            "auto_title_model": null
        }"#;
        let config: HarnessConfig = serde_json::from_str(json).unwrap();
        assert_eq!(
            config.auto_title_model, None,
            "explicit null should disable auto-titling"
        );
    }
}
