//! Domain types, configuration, and errors for the candela-harness IDE sidecar.
//!
//! Session, Message, MessageRole, SearchResult, UsageSummary, and ChatEvent are
//! re-exported from `candela-types` (generated from candela-protos).
//! HarnessConfig, HarnessError, and TransportMode remain harness-specific
//! and are defined here.

use serde::{Deserialize, Serialize};

// ── Re-exported proto-generated types ──

pub use candela_types::session::{Message, MessageRole, SearchResult, Session};

// ── Session constructor ──

/// Extension methods for creating new sessions.
#[allow(clippy::field_reassign_with_default)]
pub fn new_session(model: &str, device_id: &str) -> Session {
    let now = chrono::Utc::now();
    let id = uuid::Uuid::new_v4().to_string();
    let mut session = Session::default();
    session.id = id;
    session.title = "New Chat".to_string();
    session.model = model.to_string();
    session.device_id = device_id.to_string();
    session.created_at = now;
    session.updated_at = now;
    session
}

/// Create a new user message for a session.
#[allow(clippy::field_reassign_with_default)]
pub fn new_message(session_id: &str, role: MessageRole, content: &str) -> Message {
    let mut msg = Message::default();
    msg.id = uuid::Uuid::new_v4().to_string();
    msg.session_id = session_id.to_string();
    msg.role = role;
    msg.content = content.to_string();
    msg.created_at = chrono::Utc::now();
    msg
}

// ── Configuration ──

/// Top-level harness configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HarnessConfig {
    /// Directory for session storage.
    pub save_dir: std::path::PathBuf,
    /// Candela proxy URL for model routing.
    pub proxy_url: Option<String>,
    /// Default model identifier.
    pub model: String,
    /// Budget limit in USD. 0 = unlimited.
    // TODO: Consider using integer micro-units (i64 microdollars) instead of f64
    // to avoid floating-point rounding in budget calculations.
    pub budget_limit_usd: f64,
    /// Device ID for cross-device sync.
    pub device_id: String,
    /// Enable subagent delegation.
    pub enable_subagents: bool,
    /// Transport mode.
    pub transport: TransportMode,
    /// HTTP port (for daemon mode).
    pub http_port: u16,
    /// Model for auto-generating session titles.
    /// Some("truncate") (default) = first ~80 chars, word-boundary aware.
    /// Some("keywords") = local keyword extraction, no API call.
    /// Some("auto") = resolve cheapest model at runtime via models.list API.
    /// Some("model-name") = use a specific model for LLM summarization.
    /// None = disabled, no auto-titling.
    #[serde(default = "default_auto_title_model")]
    pub auto_title_model: Option<String>,
}

fn default_auto_title_model() -> Option<String> {
    Some("truncate".to_string())
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum TransportMode {
    #[default]
    Stdio,
    Http,
}

impl Default for HarnessConfig {
    fn default() -> Self {
        Self {
            save_dir: std::path::PathBuf::from(".candela/sessions"),
            proxy_url: None,
            model: "gemini-2.0-flash".to_string(),
            budget_limit_usd: 5.0,
            device_id: String::new(),
            enable_subagents: true,
            transport: TransportMode::Stdio,
            http_port: 8200,
            auto_title_model: Some("truncate".to_string()),
        }
    }
}

// ── Errors ──

/// Harness-specific error type.
#[derive(Debug, thiserror::Error)]
pub enum HarnessError {
    #[error("storage error: {0}")]
    Storage(String),

    #[error("serialization error: {0}")]
    Serialization(#[from] serde_json::Error),

    #[error("session not found: {0}")]
    SessionNotFound(String),

    #[error("budget exceeded: used ${used:.4} of ${limit:.4} limit")]
    BudgetExceeded { used: f64, limit: f64 },

    #[error("transport error: {0}")]
    Transport(String),

    #[error("{0}")]
    Other(#[from] anyhow::Error),
}

// ── Streaming Chat Events ──
//
// Two representations of ChatEvent coexist:
//
// 1. `ChatEvent` (struct + oneof) — used internally by the runtime and
//    Connect/gRPC backends. Generated by proto2type `domain` backend.
//
// 2. `ChatEventRpc` (flat tagged enum) — used for JSON-RPC wire format.
//    Generated by proto2type `jsonrpc` backend. Serializes directly to:
//    `{"type":"chunk","stream_id":"...","delta":"..."}`
//
// The From<&ChatEvent> for ChatEventRpc impl lives in candela-types
// (orphan rule requires it there). The handler calls ChatEventRpc::from()
// at the serialization boundary.

pub use candela_types::chat::{
    ChatEvent, ChatEventEvent, ChunkEvent, DoneEvent, ErrorEvent, StatusEvent, ToolCallEvent,
    UsageSummary,
};
pub use candela_types::chat_jsonrpc::ChatEventRpc;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_new_has_valid_defaults() {
        let session = new_session("gemini-2.0-flash", "device-1");
        assert_eq!(session.title, "New Chat");
        assert_eq!(session.model, "gemini-2.0-flash");
        assert_eq!(session.message_count, 0);
        assert!(session.deleted_at.is_none());
        assert!(!session.id.is_empty());
    }

    #[test]
    fn session_json_round_trip() {
        let session = new_session("test-model", "dev-1");
        let json = serde_json::to_string(&session).unwrap();
        let restored: Session = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.id, session.id);
        assert_eq!(restored.model, "test-model");
    }

    #[test]
    fn chat_event_json_rpc_round_trip() {
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::Done({
                let mut d = DoneEvent::default();
                d.usage = Some(UsageSummary::default());
                d
            }));
            e
        };
        // Verify the From impl + serde round-trip produces flat JSON-RPC format.
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        assert_eq!(json["type"], "done");
        assert_eq!(json["stream_id"], "s1");
    }

    #[test]
    fn message_new_has_uuid() {
        let msg = new_message("sess-1", MessageRole::User, "hello");
        assert!(!msg.id.is_empty());
        assert_eq!(msg.session_id, "sess-1");
        assert_eq!(msg.content, "hello");
    }

    #[test]
    fn harness_config_default() {
        let config = HarnessConfig::default();
        assert_eq!(config.model, "gemini-2.0-flash");
        assert_eq!(config.http_port, 8200);
    }

    #[test]
    fn test_chat_event_all_variants_json_rpc() {
        // Verify ChatEventRpc::from produces the correct flat format
        // for each variant.
        let cases: Vec<(ChatEvent, &str)> = vec![
            (
                {
                    let mut e = ChatEvent::default();
                    e.stream_id = "s1".into();
                    e.event = Some(ChatEventEvent::Chunk({
                        let mut c = ChunkEvent::default();
                        c.delta = "Hello".into();
                        c
                    }));
                    e
                },
                "chunk",
            ),
            (
                {
                    let mut e = ChatEvent::default();
                    e.stream_id = "s1".into();
                    e.event = Some(ChatEventEvent::ToolCall({
                        let mut t = ToolCallEvent::default();
                        t.call_id = "c1".into();
                        t.tool = "read_file".into();
                        t.args = serde_json::Map::new();
                        t.requires_approval = true;
                        t
                    }));
                    e
                },
                "tool_call",
            ),
            (
                {
                    let mut e = ChatEvent::default();
                    e.stream_id = "s1".into();
                    e.event = Some(ChatEventEvent::Status({
                        let mut s = StatusEvent::default();
                        s.text = "Analyzing...".into();
                        s.agent = Some("sub-1".into());
                        s
                    }));
                    e
                },
                "status",
            ),
            (
                {
                    let mut e = ChatEvent::default();
                    e.stream_id = "s1".into();
                    e.event = Some(ChatEventEvent::Error({
                        let mut err = ErrorEvent::default();
                        err.message = "rate limit".into();
                        err
                    }));
                    e
                },
                "error",
            ),
            (
                {
                    let mut e = ChatEvent::default();
                    e.stream_id = "s1".into();
                    e.event = Some(ChatEventEvent::Done({
                        let mut d = DoneEvent::default();
                        d.usage = Some(UsageSummary::default());
                        d
                    }));
                    e
                },
                "done",
            ),
        ];

        for (event, expected_type) in &cases {
            let rpc = ChatEventRpc::from(event);
            let json = serde_json::to_value(&rpc).unwrap();
            assert_eq!(
                json["type"].as_str().unwrap(),
                *expected_type,
                "wrong type for {expected_type}"
            );
            assert_eq!(json["stream_id"], "s1");
        }
    }

    #[test]
    fn test_chat_event_json_rpc_chunk_has_delta() {
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::Chunk({
                let mut c = ChunkEvent::default();
                c.delta = "Hello world".into();
                c
            }));
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        assert_eq!(json["delta"], "Hello world");
    }

    #[test]
    fn test_chat_event_json_rpc_status_with_agent() {
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::Status({
                let mut s = StatusEvent::default();
                s.text = "Working...".into();
                s.agent = Some("sub-agent".into());
                s
            }));
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        assert_eq!(json["agent"], "sub-agent");
    }

    #[test]
    fn test_chat_event_json_rpc_status_without_agent() {
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::Status({
                let mut s = StatusEvent::default();
                s.text = "Working...".into();
                s
            }));
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        // agent should be absent (skip_serializing_if = "Option::is_none").
        assert!(json.get("agent").is_none());
    }

    #[test]
    fn test_new_message_sets_defaults() {
        let msg = new_message("sess-1", MessageRole::Assistant, "hi");
        // model should be None (from Default).
        assert_eq!(msg.model, None);
        // token_count should be None.
        assert_eq!(msg.token_count, None);
        // sequence defaults to 0 (DB auto-assigns on insert).
        assert_eq!(msg.sequence, 0);
        // cost_usd should be None.
        assert_eq!(msg.cost_usd, None);
    }

    #[test]
    fn test_serde_missing_auto_title_model_defaults_to_truncate() {
        // Configs from older versions won't have auto_title_model.
        // The serde default should fill in Some("truncate"), not None.
        let json = r#"{
            "save_dir": ".candela/sessions",
            "model": "gemini-2.0-flash",
            "budget_limit_usd": 5.0,
            "device_id": "",
            "enable_subagents": true,
            "transport": "stdio",
            "http_port": 8200
        }"#;
        let config: HarnessConfig = serde_json::from_str(json).unwrap();
        assert_eq!(
            config.auto_title_model,
            Some("truncate".to_string()),
            "missing auto_title_model should default to Some(\"truncate\")"
        );
    }

    #[test]
    fn test_serde_explicit_none_auto_title_model() {
        // Explicitly set to null = disabled.
        let json = r#"{
            "save_dir": ".candela/sessions",
            "model": "gemini-2.0-flash",
            "budget_limit_usd": 5.0,
            "device_id": "",
            "enable_subagents": true,
            "transport": "stdio",
            "http_port": 8200,
            "auto_title_model": null
        }"#;
        let config: HarnessConfig = serde_json::from_str(json).unwrap();
        assert_eq!(
            config.auto_title_model, None,
            "explicit null should disable auto-titling"
        );
    }

    #[test]
    fn test_chat_event_rpc_tool_call_args_fidelity() {
        // Verify serde_json::Map → serde_json::Value::Object preserves all data.
        let mut args = serde_json::Map::new();
        args.insert("path".into(), serde_json::json!("/tmp/foo.rs"));
        args.insert("recursive".into(), serde_json::json!(true));
        args.insert("depth".into(), serde_json::json!(3));

        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::ToolCall({
                let mut t = ToolCallEvent::default();
                t.call_id = "c1".into();
                t.tool = "read_file".into();
                t.args = args.clone();
                t.requires_approval = false;
                t
            }));
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        // All 3 args must survive the conversion.
        assert_eq!(json["args"]["path"], "/tmp/foo.rs");
        assert_eq!(json["args"]["recursive"], true);
        assert_eq!(json["args"]["depth"], 3);
    }

    #[test]
    fn test_chat_event_rpc_none_event_becomes_error() {
        // A ChatEvent with event: None should map to Error with UNKNOWN code.
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = None;
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        assert_eq!(json["type"], "error");
        assert_eq!(json["message"], "unknown event");
        assert_eq!(json["code"], "UNKNOWN");
    }

    #[test]
    fn test_chat_event_rpc_done_without_usage() {
        // Done with usage: None should omit usage field entirely.
        let event = {
            let mut e = ChatEvent::default();
            e.stream_id = "s1".into();
            e.event = Some(ChatEventEvent::Done(DoneEvent::default()));
            e
        };
        let rpc = ChatEventRpc::from(&event);
        let json = serde_json::to_value(&rpc).unwrap();
        assert_eq!(json["type"], "done");
        assert!(
            json.get("usage").is_none(),
            "usage should be absent when None"
        );
    }

    #[test]
    fn test_chat_event_rpc_deserialization_round_trip() {
        // Verify we can deserialize a JSON-RPC event back into ChatEventRpc.
        let wire_json = r#"{"type":"chunk","stream_id":"s42","delta":"hello"}"#;
        let rpc: ChatEventRpc = serde_json::from_str(wire_json).unwrap();
        match rpc {
            ChatEventRpc::Chunk { stream_id, delta } => {
                assert_eq!(stream_id, "s42");
                assert_eq!(delta, "hello");
            }
            other => panic!("expected Chunk, got {other:?}"),
        }
    }
}
