//! ConnectRPC service implementation for the harness.
//!
//! Domain types (Session, ChatEvent, etc.) come from candela.types protos.
//! Request/response wrappers come from candela.v1.harness_service proto.
//! Conversions between domain and buffa types will be auto-generated by
//! proto2type's buffa backend once vendored.

use std::sync::{Arc, Mutex};

use buffa::MessageField;
use candela_core::harness::{self, ChatEvent, ChatEventEvent, HarnessError, new_session};
use candela_harness_chat::ChatRuntime;
use candela_harness_storage::{Database, SearchIndex};
use connectrpc::{
    ConnectError, RequestContext, Response, ServiceRequest, ServiceResult, ServiceStream,
};

use crate::proto::candela::types as proto_types;
use crate::proto::candela::v1::*;

/// ConnectRPC service implementation backed by ChatRuntime + Database.
pub struct HarnessServiceImpl {
    pub chat: Arc<ChatRuntime>,
    pub db: Arc<Mutex<Database>>,
    pub search: Arc<Mutex<SearchIndex>>,
}

// ── Domain ↔ Proto conversions ──
// Adapter: candela_core domain types ↔ candela.types buffa wire types.
// ChatEvent is now the unified type from candela_types::chat, re-exported
// via candela_core. These converters will be replaced by proto2type-generated
// buffa From impls once vendored.

#[allow(clippy::field_reassign_with_default, clippy::useless_conversion)]
fn domain_session_to_proto(s: &harness::Session) -> proto_types::Session {
    let mut session = proto_types::Session::default();
    session.id = s.id.clone().into();
    session.title = s.title.clone().into();
    session.model = s.model.clone().into();
    session.message_count = s.message_count;
    session.total_tokens = s.total_tokens;
    session.total_cost_usd = s.total_cost_usd;
    session.device_id = s.device_id.clone().into();
    session.created_at = MessageField::some(chrono_to_buffa_timestamp(&s.created_at));
    session.updated_at = MessageField::some(chrono_to_buffa_timestamp(&s.updated_at));
    session.deleted_at = match &s.deleted_at {
        Some(dt) => MessageField::some(chrono_to_buffa_timestamp(dt)),
        None => MessageField::none(),
    };
    session
}

#[allow(clippy::field_reassign_with_default, clippy::useless_conversion)]
fn domain_chat_event_to_proto(event: &ChatEvent) -> SendMessageResponse {
    let mut ce = proto_types::ChatEvent::default();
    ce.stream_id = event.stream_id.clone().into();

    ce.event = event.event.as_ref().map(|inner| match inner {
        ChatEventEvent::Chunk(c) => {
            let mut e = proto_types::ChunkEvent::default();
            e.delta = c.delta.clone().into();
            proto_types::__buffa::oneof::chat_event::Event::Chunk(Box::new(e))
        }
        ChatEventEvent::Done(d) => {
            let mut e = proto_types::DoneEvent::default();
            if let Some(usage) = &d.usage {
                let mut u = proto_types::UsageSummary::default();
                u.prompt_tokens = usage.prompt_tokens;
                u.completion_tokens = usage.completion_tokens;
                u.total_tokens = usage.total_tokens;
                u.total_cost_usd = usage.total_cost_usd;
                u.model = usage.model.clone().into();
                e.usage = MessageField::some(u);
            }
            proto_types::__buffa::oneof::chat_event::Event::Done(Box::new(e))
        }
        ChatEventEvent::Error(err) => {
            let mut e = proto_types::ErrorEvent::default();
            e.message = err.message.clone().into();
            e.code = err.code.as_deref().map(Into::into);
            proto_types::__buffa::oneof::chat_event::Event::Error(Box::new(e))
        }
        ChatEventEvent::Status(s) => {
            let mut e = proto_types::StatusEvent::default();
            e.text = s.text.clone().into();
            e.agent = s.agent.as_deref().map(Into::into);
            proto_types::__buffa::oneof::chat_event::Event::Status(Box::new(e))
        }
        ChatEventEvent::ToolCall(tc) => {
            let mut e = proto_types::ToolCallEvent::default();
            e.call_id = tc.call_id.clone().into();
            e.tool = tc.tool.clone().into();
            e.args = MessageField::some(
                serde_json::from_value(serde_json::Value::Object(tc.args.clone()))
                    .unwrap_or_default(),
            );
            e.requires_approval = tc.requires_approval;
            proto_types::__buffa::oneof::chat_event::Event::ToolCall(Box::new(e))
        }
    });

    let mut resp = SendMessageResponse::default();
    resp.event = MessageField::some(ce);
    resp
}

#[allow(clippy::field_reassign_with_default)]
fn chrono_to_buffa_timestamp(
    dt: &chrono::DateTime<chrono::Utc>,
) -> buffa_types::google::protobuf::Timestamp {
    let mut ts = buffa_types::google::protobuf::Timestamp::default();
    ts.seconds = dt.timestamp();
    ts.nanos = dt.timestamp_subsec_nanos() as i32;
    ts
}

#[allow(
    clippy::field_reassign_with_default,
    clippy::useless_conversion,
    clippy::redundant_closure,
    clippy::manual_async_fn,
    refining_impl_trait
)]
impl HarnessService for HarnessServiceImpl {
    fn send_message(
        &self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, SendMessageRequest>,
    ) -> impl std::future::Future<Output = ServiceResult<ServiceStream<SendMessageResponse>>> + Send
    {
        let session_id = request.session_id.to_string();
        let content = request.content.to_string();
        let chat = self.chat.clone();

        async move {
            let (_stream_id, event_stream) = chat
                .clone()
                .send_message(&session_id, &content)
                .await
                .map_err(|e| match e {
                    HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                    other => ConnectError::internal(other.to_string()),
                })?;

            use tokio_stream::StreamExt;
            let stream = event_stream.map(|event| Ok(domain_chat_event_to_proto(&event)));
            Ok(Response::new(Box::pin(stream) as ServiceStream<_>))
        }
    }

    fn list_sessions<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, ListSessionsRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<ListSessionsResponse> + Send + use<'a>>,
    > + Send {
        // page_size takes precedence over deprecated limit
        let limit = (if request.page_size > 0 {
            request.page_size
        } else {
            request.limit
        })
        .clamp(0, 200) as i64;
        let offset = request.offset.max(0) as i64;

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let total_count =
                db.count_sessions()
                    .map_err(|e| ConnectError::internal(e.to_string()))? as i32;
            let sessions = db
                .list_sessions(limit, offset)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let proto_sessions: Vec<proto_types::Session> =
                sessions.iter().map(domain_session_to_proto).collect();
            let total = proto_sessions.len() as i32;

            let mut resp = ListSessionsResponse::default();
            resp.sessions = proto_sessions;
            resp.total = total; // deprecated — kept for backward compat
            resp.total_count = total_count;
            Ok(Response::new(resp))
        }
    }

    fn create_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, CreateSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<CreateSessionResponse> + Send + use<'a>>,
    > + Send {
        let model = request.model.to_string();
        let device_id = request.device_id.to_string();

        async move {
            let session = new_session(&model, &device_id);

            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.create_session(&session)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let mut resp = CreateSessionResponse::default();
            resp.session = MessageField::some(domain_session_to_proto(&session));
            Ok(Response::new(resp))
        }
    }

    fn get_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, GetSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<GetSessionResponse> + Send + use<'a>>,
    > + Send {
        let session_id = request.session_id.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let session = db.get_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;
            let mut resp = GetSessionResponse::default();
            resp.session = MessageField::some(domain_session_to_proto(&session));
            Ok(Response::new(resp))
        }
    }

    fn delete_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, DeleteSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<DeleteSessionResponse> + Send + use<'a>>,
    > + Send {
        let session_id = request.session_id.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.delete_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;

            Ok(Response::new(DeleteSessionResponse::default()))
        }
    }

    fn edit_session_title<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, EditSessionTitleRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<
            impl connectrpc::Encodable<EditSessionTitleResponse> + Send + use<'a>,
        >,
    > + Send {
        let session_id = request.session_id.to_string();
        let title = request.title.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.update_session_title(&session_id, &title)
                .map_err(|e| match e {
                    HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                    other => ConnectError::internal(other.to_string()),
                })?;
            let session = db.get_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;

            let mut resp = EditSessionTitleResponse::default();
            resp.session = MessageField::some(domain_session_to_proto(&session));
            Ok(Response::new(resp))
        }
    }

    fn search_messages<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, SearchMessagesRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<SearchMessagesResponse> + Send + use<'a>>,
    > + Send {
        let query = request.query.to_string();
        let limit = request.limit.max(0) as i64;

        async move {
            let search = self
                .search
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let results = search
                .search(&query, limit)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let proto_results: Vec<proto_types::SearchResult> = results
                .iter()
                .map(|r| {
                    let mut sr = proto_types::SearchResult::default();
                    sr.message_preview = r.message_preview.clone().into();
                    sr.session_id = r.session_id.clone().into();
                    sr.message_id = r.message_id.clone().into();
                    sr.session_title = r.session_title.clone().into();
                    sr.role = buffa::EnumValue::from(r.role as i32);
                    sr.score = r.score;
                    sr.created_at = MessageField::some(chrono_to_buffa_timestamp(&r.created_at));
                    sr
                })
                .collect();

            let mut resp = SearchMessagesResponse::default();
            resp.results = proto_results;
            Ok(Response::new(resp))
        }
    }

    fn health<'a>(
        &'a self,
        _ctx: RequestContext,
        _request: ServiceRequest<'_, HealthRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<HealthResponse> + Send + use<'a>>,
    > + Send {
        async move {
            let mut resp = HealthResponse::default();
            resp.status = "ok".into();
            resp.version = env!("CARGO_PKG_VERSION").into();
            Ok(Response::new(resp))
        }
    }
}
