//! ConnectRPC service implementation for the harness.
//!
//! Domain types (Session, ChatEvent, etc.) come from candela.types protos.
//! Request/response wrappers come from candela.v1.harness_service proto.
//! Conversions between domain and buffa types will be auto-generated by
//! proto2type's buffa backend once vendored.

use std::sync::{Arc, Mutex};

use buffa::MessageField;
use candela_core::harness::{ChatEvent, HarnessError, new_session};
use candela_harness_chat::ChatRuntime;
use candela_harness_storage::{Database, SearchIndex};
use connectrpc::{
    ConnectError, RequestContext, Response, ServiceRequest, ServiceResult, ServiceStream,
};

use crate::proto::candela::types as proto_types;
use crate::proto::candela::v1::*;

/// ConnectRPC service implementation backed by ChatRuntime + Database.
pub struct HarnessServiceImpl {
    pub chat: Arc<ChatRuntime>,
    pub db: Arc<Mutex<Database>>,
    pub search: Arc<Mutex<SearchIndex>>,
}

// ── Domain ↔ Proto conversions ──
// Generated From/TryFrom impls live in crate::converters (proto2type buffa backend).
// Only service-level wrappers (e.g. wrapping ChatEvent in SendMessageResponse)
// remain hand-written here.

/// Wrap a domain ChatEvent into a SendMessageResponse for streaming.
#[allow(clippy::field_reassign_with_default)]
fn domain_chat_event_to_proto(event: &ChatEvent) -> SendMessageResponse {
    let ce: proto_types::ChatEvent = event.into();
    let mut resp = SendMessageResponse::default();
    resp.event = MessageField::some(ce);
    resp
}

#[allow(
    clippy::field_reassign_with_default,
    clippy::useless_conversion,
    clippy::redundant_closure,
    clippy::manual_async_fn,
    refining_impl_trait
)]
impl HarnessService for HarnessServiceImpl {
    fn send_message(
        &self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, SendMessageRequest>,
    ) -> impl std::future::Future<Output = ServiceResult<ServiceStream<SendMessageResponse>>> + Send
    {
        let session_id = request.session_id.to_string();
        let content = request.content.to_string();
        let chat = self.chat.clone();

        async move {
            let (_stream_id, event_stream) = chat
                .clone()
                .send_message(&session_id, &content)
                .await
                .map_err(|e| match e {
                    HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                    other => ConnectError::internal(other.to_string()),
                })?;

            use tokio_stream::StreamExt;
            let stream = event_stream.map(|event| Ok(domain_chat_event_to_proto(&event)));
            Ok(Response::new(Box::pin(stream) as ServiceStream<_>))
        }
    }

    fn list_sessions<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, ListSessionsRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<ListSessionsResponse> + Send + use<'a>>,
    > + Send {
        // page_size takes precedence over deprecated limit; default 50
        let raw = if request.page_size > 0 {
            request.page_size
        } else if request.limit > 0 {
            request.limit
        } else {
            50
        };
        let limit = raw.clamp(0, 200) as i64;
        let offset = request.offset.max(0) as i64;

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let total_count =
                db.count_sessions()
                    .map_err(|e| ConnectError::internal(e.to_string()))? as i32;
            let sessions = db
                .list_sessions(limit, offset)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let proto_sessions: Vec<proto_types::Session> =
                sessions.iter().map(proto_types::Session::from).collect();
            let total = proto_sessions.len() as i32;

            let mut resp = ListSessionsResponse::default();
            resp.sessions = proto_sessions;
            resp.total = total; // deprecated — kept for backward compat
            resp.total_count = total_count;
            Ok(Response::new(resp))
        }
    }

    fn create_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, CreateSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<CreateSessionResponse> + Send + use<'a>>,
    > + Send {
        let model = request.model.to_string();
        let device_id = request.device_id.to_string();

        async move {
            let session = new_session(&model, &device_id);

            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.create_session(&session)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let mut resp = CreateSessionResponse::default();
            resp.session = MessageField::some(proto_types::Session::from(&session));
            Ok(Response::new(resp))
        }
    }

    fn get_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, GetSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<GetSessionResponse> + Send + use<'a>>,
    > + Send {
        let session_id = request.session_id.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let session = db.get_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;
            let mut resp = GetSessionResponse::default();
            resp.session = MessageField::some(proto_types::Session::from(&session));
            Ok(Response::new(resp))
        }
    }

    fn delete_session<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, DeleteSessionRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<DeleteSessionResponse> + Send + use<'a>>,
    > + Send {
        let session_id = request.session_id.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.delete_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;

            Ok(Response::new(DeleteSessionResponse::default()))
        }
    }

    fn edit_session_title<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, EditSessionTitleRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<
            impl connectrpc::Encodable<EditSessionTitleResponse> + Send + use<'a>,
        >,
    > + Send {
        let session_id = request.session_id.to_string();
        let title = request.title.to_string();

        async move {
            let db = self
                .db
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            db.update_session_title(&session_id, &title)
                .map_err(|e| match e {
                    HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                    other => ConnectError::internal(other.to_string()),
                })?;
            let session = db.get_session(&session_id).map_err(|e| match e {
                HarnessError::SessionNotFound(msg) => ConnectError::not_found(msg),
                other => ConnectError::internal(other.to_string()),
            })?;

            let mut resp = EditSessionTitleResponse::default();
            resp.session = MessageField::some(proto_types::Session::from(&session));
            Ok(Response::new(resp))
        }
    }

    fn search_messages<'a>(
        &'a self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, SearchMessagesRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<SearchMessagesResponse> + Send + use<'a>>,
    > + Send {
        let query = request.query.to_string();
        let limit = request.limit.max(0) as i64;

        async move {
            let search = self
                .search
                .lock()
                .map_err(|e| ConnectError::internal(format!("lock failed: {e}")))?;
            let results = search
                .search(&query, limit)
                .map_err(|e| ConnectError::internal(e.to_string()))?;

            let proto_results: Vec<proto_types::SearchResult> = results
                .iter()
                .map(proto_types::SearchResult::from)
                .collect();

            let mut resp = SearchMessagesResponse::default();
            resp.results = proto_results;
            Ok(Response::new(resp))
        }
    }

    fn health<'a>(
        &'a self,
        _ctx: RequestContext,
        _request: ServiceRequest<'_, HealthRequest>,
    ) -> impl std::future::Future<
        Output = ServiceResult<impl connectrpc::Encodable<HealthResponse> + Send + use<'a>>,
    > + Send {
        async move {
            let mut resp = HealthResponse::default();
            resp.status = "ok".into();
            resp.version = env!("CARGO_PKG_VERSION").into();
            Ok(Response::new(resp))
        }
    }
}
