// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.4.2
// source: candela/types/chat.proto
// backend: buffa

use candela_types::prelude::*;

use crate::proto::candela::types as __buffa_mod;

#[derive(Debug)]
pub enum ConversionError {
    InvalidEnumValue(i32),
    InvalidStructValue,
}

impl std::fmt::Display for ConversionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidEnumValue(v) => write!(f, "invalid enum value: {v}"),
            Self::InvalidStructValue => write!(f, "invalid struct value"),
        }
    }
}

impl std::error::Error for ConversionError {}

#[allow(clippy::field_reassign_with_default)]
impl From<&ChatEvent> for __buffa_mod::ChatEvent {
    fn from(d: &ChatEvent) -> Self {
        let mut b = Self::default();
        b.stream_id = d.stream_id.clone().into();
        b.event = d.event.as_ref().map(|v| match v {
            ChatEventEvent::Chunk(inner) => {
                let converted: __buffa_mod::ChunkEvent = inner.into();
                __buffa_mod::__buffa::oneof::chat_event::Event::Chunk(Box::new(converted))
            }
            ChatEventEvent::ToolCall(inner) => {
                let converted: __buffa_mod::ToolCallEvent = inner.into();
                __buffa_mod::__buffa::oneof::chat_event::Event::ToolCall(Box::new(converted))
            }
            ChatEventEvent::Status(inner) => {
                let converted: __buffa_mod::StatusEvent = inner.into();
                __buffa_mod::__buffa::oneof::chat_event::Event::Status(Box::new(converted))
            }
            ChatEventEvent::Done(inner) => {
                let converted: __buffa_mod::DoneEvent = inner.into();
                __buffa_mod::__buffa::oneof::chat_event::Event::Done(Box::new(converted))
            }
            ChatEventEvent::Error(inner) => {
                let converted: __buffa_mod::ErrorEvent = inner.into();
                __buffa_mod::__buffa::oneof::chat_event::Event::Error(Box::new(converted))
            }
        });
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::ChatEvent> for ChatEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::ChatEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.stream_id = b.stream_id.to_string();
        d.event = match &b.event {
            Some(__buffa_mod::__buffa::oneof::chat_event::Event::Chunk(inner)) => {
                Some(ChatEventEvent::Chunk(inner.as_ref().try_into()?))
            }
            Some(__buffa_mod::__buffa::oneof::chat_event::Event::ToolCall(inner)) => {
                Some(ChatEventEvent::ToolCall(inner.as_ref().try_into()?))
            }
            Some(__buffa_mod::__buffa::oneof::chat_event::Event::Status(inner)) => {
                Some(ChatEventEvent::Status(inner.as_ref().try_into()?))
            }
            Some(__buffa_mod::__buffa::oneof::chat_event::Event::Done(inner)) => {
                Some(ChatEventEvent::Done(inner.as_ref().try_into()?))
            }
            Some(__buffa_mod::__buffa::oneof::chat_event::Event::Error(inner)) => {
                Some(ChatEventEvent::Error(inner.as_ref().try_into()?))
            }
            None => None,
        };
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&ChunkEvent> for __buffa_mod::ChunkEvent {
    fn from(d: &ChunkEvent) -> Self {
        let mut b = Self::default();
        b.delta = d.delta.clone().into();
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::ChunkEvent> for ChunkEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::ChunkEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.delta = b.delta.to_string();
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&ToolCallEvent> for __buffa_mod::ToolCallEvent {
    fn from(d: &ToolCallEvent) -> Self {
        let mut b = Self::default();
        b.call_id = d.call_id.clone().into();
        b.tool = d.tool.clone().into();
        b.args = buffa::MessageField::some(
            serde_json::from_value(serde_json::Value::Object(d.args.clone()))
                .expect("failed to convert serde_json::Map to protobuf Struct"),
        );
        b.requires_approval = d.requires_approval;
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::ToolCallEvent> for ToolCallEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::ToolCallEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.call_id = b.call_id.to_string();
        d.tool = b.tool.to_string();
        d.args = match serde_json::to_value(&*b.args)
            .map_err(|_| ConversionError::InvalidStructValue)?
        {
            serde_json::Value::Object(m) => m,
            _ => return Err(ConversionError::InvalidStructValue),
        };
        d.requires_approval = b.requires_approval;
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&StatusEvent> for __buffa_mod::StatusEvent {
    fn from(d: &StatusEvent) -> Self {
        let mut b = Self::default();
        b.text = d.text.clone().into();
        b.agent = d.agent.as_deref().map(Into::into);
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::StatusEvent> for StatusEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::StatusEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.text = b.text.to_string();
        d.agent = b.agent.as_ref().map(|s| s.to_string());
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&DoneEvent> for __buffa_mod::DoneEvent {
    fn from(d: &DoneEvent) -> Self {
        let mut b = Self::default();
        b.usage = match &d.usage {
            Some(v) => buffa::MessageField::some(v.into()),
            None => buffa::MessageField::none(),
        };
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::DoneEvent> for DoneEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::DoneEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.usage = match b.usage.as_option() {
            Some(v) => Some(v.try_into()?),
            None => None,
        };
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&ErrorEvent> for __buffa_mod::ErrorEvent {
    fn from(d: &ErrorEvent) -> Self {
        let mut b = Self::default();
        b.message = d.message.clone().into();
        b.code = d.code.as_deref().map(Into::into);
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::ErrorEvent> for ErrorEvent {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::ErrorEvent) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.message = b.message.to_string();
        d.code = b.code.as_ref().map(|s| s.to_string());
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&UsageSummary> for __buffa_mod::UsageSummary {
    fn from(d: &UsageSummary) -> Self {
        let mut b = Self::default();
        b.prompt_tokens = d.prompt_tokens;
        b.completion_tokens = d.completion_tokens;
        b.total_tokens = d.total_tokens;
        b.total_cost_usd = d.total_cost_usd;
        b.model = d.model.clone().into();
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::UsageSummary> for UsageSummary {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::UsageSummary) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.prompt_tokens = b.prompt_tokens;
        d.completion_tokens = b.completion_tokens;
        d.total_tokens = b.total_tokens;
        d.total_cost_usd = b.total_cost_usd;
        d.model = b.model.to_string();
        Ok(d)
    }
}
