// Code generated by proto2type. DO NOT EDIT.
// proto2type v0.4.2
// source: candela/types/session.proto
// backend: buffa

use candela_types::prelude::*;
use chrono::{DateTime, Utc};

use crate::proto::candela::types as __buffa_mod;

#[derive(Debug)]
pub enum ConversionError {
    InvalidTimestamp { seconds: i64, nanos: i32 },
    InvalidEnumValue(i32),
    MissingRequiredField(&'static str),
}

impl std::fmt::Display for ConversionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidTimestamp { seconds, nanos } => {
                write!(f, "invalid timestamp: {seconds}s {nanos}ns")
            }
            Self::InvalidEnumValue(v) => write!(f, "invalid enum value: {v}"),
            Self::MissingRequiredField(field) => write!(f, "missing required field: {field}"),
        }
    }
}

impl std::error::Error for ConversionError {}

/// Converts a chrono DateTime<Utc> to a buffa protobuf Timestamp.
#[allow(dead_code)]
fn chrono_to_buffa_timestamp(dt: &DateTime<Utc>) -> buffa_types::google::protobuf::Timestamp {
    let mut ts = buffa_types::google::protobuf::Timestamp::default();
    ts.seconds = dt.timestamp();
    ts.nanos = dt.timestamp_subsec_nanos() as i32;
    ts
}

/// Converts a buffa protobuf Timestamp to a chrono DateTime<Utc>.
#[allow(dead_code)]
fn buffa_timestamp_to_chrono(
    ts: &buffa_types::google::protobuf::Timestamp,
) -> Result<DateTime<Utc>, ConversionError> {
    DateTime::from_timestamp(ts.seconds, ts.nanos as u32).ok_or(ConversionError::InvalidTimestamp {
        seconds: ts.seconds,
        nanos: ts.nanos,
    })
}

#[allow(clippy::field_reassign_with_default)]
impl From<&Session> for __buffa_mod::Session {
    fn from(d: &Session) -> Self {
        let mut b = Self::default();
        b.id = d.id.clone().into();
        b.title = d.title.clone().into();
        b.model = d.model.clone().into();
        b.message_count = d.message_count;
        b.total_tokens = d.total_tokens;
        b.total_cost_usd = d.total_cost_usd;
        b.device_id = d.device_id.clone().into();
        b.created_at = buffa::MessageField::some(chrono_to_buffa_timestamp(&d.created_at));
        b.updated_at = buffa::MessageField::some(chrono_to_buffa_timestamp(&d.updated_at));
        b.deleted_at = match &d.deleted_at {
            Some(dt) => buffa::MessageField::some(chrono_to_buffa_timestamp(dt)),
            None => buffa::MessageField::none(),
        };
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::Session> for Session {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::Session) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.id = b.id.to_string();
        d.title = b.title.to_string();
        d.model = b.model.to_string();
        d.message_count = b.message_count;
        d.total_tokens = b.total_tokens;
        d.total_cost_usd = b.total_cost_usd;
        d.device_id = b.device_id.to_string();
        d.created_at = buffa_timestamp_to_chrono(
            b.created_at
                .as_option()
                .ok_or(ConversionError::MissingRequiredField("created_at"))?,
        )?;
        d.updated_at = buffa_timestamp_to_chrono(
            b.updated_at
                .as_option()
                .ok_or(ConversionError::MissingRequiredField("updated_at"))?,
        )?;
        d.deleted_at = match b.deleted_at.as_option() {
            Some(ts) => Some(buffa_timestamp_to_chrono(ts)?),
            None => None,
        };
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&Message> for __buffa_mod::Message {
    fn from(d: &Message) -> Self {
        let mut b = Self::default();
        b.id = d.id.clone().into();
        b.session_id = d.session_id.clone().into();
        b.role = buffa::EnumValue::from(d.role as i32);
        b.content = d.content.clone().into();
        b.model = d.model.as_deref().map(Into::into);
        b.token_count = d.token_count;
        b.cost_usd = d.cost_usd;
        b.created_at = buffa::MessageField::some(chrono_to_buffa_timestamp(&d.created_at));
        b.sequence = d.sequence;
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::Message> for Message {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::Message) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.id = b.id.to_string();
        d.session_id = b.session_id.to_string();
        d.role = MessageRole::from_i32(b.role.to_i32())
            .ok_or(ConversionError::InvalidEnumValue(b.role.to_i32()))?;
        d.content = b.content.to_string();
        d.model = b.model.as_ref().map(|s| s.to_string());
        d.token_count = b.token_count;
        d.cost_usd = b.cost_usd;
        d.created_at = buffa_timestamp_to_chrono(
            b.created_at
                .as_option()
                .ok_or(ConversionError::MissingRequiredField("created_at"))?,
        )?;
        d.sequence = b.sequence;
        Ok(d)
    }
}

#[allow(clippy::field_reassign_with_default)]
impl From<&SearchResult> for __buffa_mod::SearchResult {
    fn from(d: &SearchResult) -> Self {
        let mut b = Self::default();
        b.session_id = d.session_id.clone().into();
        b.message_id = d.message_id.clone().into();
        b.session_title = d.session_title.clone().into();
        b.message_preview = d.message_preview.clone().into();
        b.role = buffa::EnumValue::from(d.role as i32);
        b.score = d.score;
        b.created_at = buffa::MessageField::some(chrono_to_buffa_timestamp(&d.created_at));
        b
    }
}

#[allow(clippy::field_reassign_with_default)]
impl TryFrom<&__buffa_mod::SearchResult> for SearchResult {
    type Error = ConversionError;

    fn try_from(b: &__buffa_mod::SearchResult) -> Result<Self, Self::Error> {
        let mut d = Self::default();
        d.session_id = b.session_id.to_string();
        d.message_id = b.message_id.to_string();
        d.session_title = b.session_title.to_string();
        d.message_preview = b.message_preview.to_string();
        d.role = MessageRole::from_i32(b.role.to_i32())
            .ok_or(ConversionError::InvalidEnumValue(b.role.to_i32()))?;
        d.score = b.score;
        d.created_at = buffa_timestamp_to_chrono(
            b.created_at
                .as_option()
                .ok_or(ConversionError::MissingRequiredField("created_at"))?,
        )?;
        Ok(d)
    }
}
