apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "candela-server.fullname" . }}-config
  labels:
    {{- include "candela-server.labels" . | nindent 4 }}
data:
  candela.yaml: |
    server:
      port: {{ .Values.server.port }}
    storage:
      backend: {{ .Values.storage.backend }}
      {{- if eq .Values.storage.backend "duckdb" }}
      duckdb:
        path: {{ .Values.storage.duckdb.path }}/candela.db
      {{- end }}
      {{- if eq .Values.storage.backend "bigquery" }}
      bigquery:
        project_id: {{ .Values.storage.bigquery.projectId }}
        dataset: {{ .Values.storage.bigquery.dataset }}
      {{- end }}
    proxy:
      enabled: {{ .Values.proxy.enabled }}
    catalog:
      backend: {{ .Values.catalog.backend }}
